"""Option C, C1A - bounded canary reconciliation against decoded OrderFilled rows.

CODE / TEST ONLY. No network call. No Dune call. No API/RPC call performed by
this module or by Claude. This module CONSUMES a Dune CSV export that the user
fetches manually, per the documented flow in project_context/DUNE_DATA_NOTES.md
section 7, using the query text generated by
scripts/price_source_option_c_c1a_manifest.py.

Governing specs:
- project_context/SPEC_price_source_option_c_onchain.md (Revision 3)
- project_context/SPEC_price_source_option_c_onchain_C1R_addendum.md (Patch 1)

What this file IS:
  - A reconciliation pass: given the fixed C1A selector manifest (output of the
    manifest builder) and a Dune CSV export of decoded OrderFilled rows, it
    validates schema/precision, enforces hard per-condition and global row caps
    with fail-fast, tags each row's matched side (side_0/side_1) by raw token
    match ONLY (no interpretation), and compares the retrieved tx_hash set
    against LOCAL trades for the same fixed conditions/windows/token pairs to
    produce a coverage diagnostic - not a price artifact.

What this file is NOT (hard non-goals, enforced):
  - No canonical_side_price, no target, no score, no probe feature.
  - No OrdersMatched. No wallet aggregation beyond raw per-row asset/amount
    fields already on the event row.
  - Coverage diagnostics only. A non-halt run reports `C1_CANARY_EXECUTED_NEEDS_REVIEW`,
    never `C1_CANARY_DESIGN_CLEAR` - this module never self-certifies design-clear
    status. `C1_CANARY_DESIGN_CLEAR` is a label the Orchestrator applies, if
    warranted, only after reviewing the persisted artifacts by hand.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
from collections import defaultdict
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple

PHASE = "OPTION_C_C1A_BOUNDED_CANARY"
AUTHORIZED_SCOPE = "OPTION_C_C1A_CANARY_RECONCILIATION_ONLY"

REQUIRED_EVENT_FIELDS = (
    "condition_id",
    "tx_hash",
    "block_time",
    "makerAssetId",
    "takerAssetId",
    "makerAmountFilled",
    "takerAmountFilled",
    "source_provenance",
)

_SCI_RE = re.compile(r"[eE]")
_INT_RE = re.compile(r"^[0-9]+$")

# tx_hash_relation values for row-level artifacts (patch requirement 4).
REL_DUNE_ONLY = "DUNE_ONLY"
REL_LOCAL_ONLY = "LOCAL_ONLY"
REL_OVERLAP = "OVERLAP"

# ---------------------------------------------------------------------------
# Stop / outcome codes (C1R addendum section 9, extended by this patch)
# ---------------------------------------------------------------------------
C1_SOURCE_SCHEMA_UNVERIFIED = "C1_SOURCE_SCHEMA_UNVERIFIED"
C1_ORDERING_KEY_MISSING = "C1_ORDERING_KEY_MISSING"
C1_ROW_EXPLOSION = "C1_ROW_EXPLOSION"
C1_LOCAL_TX_HASH_REPRODUCTION_ONLY = "C1_LOCAL_TX_HASH_REPRODUCTION_ONLY"
C1_INDEXER_SHAPED = "C1_INDEXER_SHAPED"
C1_SIDE_IDENTITY_UNRESOLVED = "C1_SIDE_IDENTITY_UNRESOLVED"

# New in this patch: an empty Dune export is a distinct, non-clear outcome -
# it must never fall through to a "clean" result. It is raised as a CanaryHalt
# like every other non-success path, not silently treated as vacuously OK.
C1_SOURCE_EMPTY = "C1_SOURCE_EMPTY"

# New in this patch: the automatic outcome of a non-halting run. This code
# means "ran to completion without tripping a hard stop" - nothing more. It is
# NOT a design-clear verdict.
C1_CANARY_EXECUTED_NEEDS_REVIEW = "C1_CANARY_EXECUTED_NEEDS_REVIEW"

# Retained as a defined label only. This module never assigns this value to
# any run automatically - it exists so the Orchestrator has a fixed, agreed
# string to write into a review record after manually inspecting
# c1a_canary_result.json / the row-level artifacts and deciding the pilot
# mechanism itself is clean. Code must never emit this on its own.
C1_CANARY_DESIGN_CLEAR = "C1_CANARY_DESIGN_CLEAR"


class DataExportPrecisionLoss(ValueError):
    """Fail-loud on scientific notation / float-mangled event fields."""


class CanaryHalt(RuntimeError):
    """Raised with a typed stop code; caller persists partial evidence before
    halting (persist-before-halt discipline, mirroring the accepted Option B
    B0 diagnostic design).

    `partial_coverage` / `partial_tagged_rows` / `partial_raw_rows` carry
    whatever evidence had already been accumulated at the moment of the halt,
    so the caller can always write row-level artifacts even on a hard stop -
    not just on a clean run."""

    def __init__(
        self,
        code: str,
        detail: str = "",
        partial_coverage: Optional[Dict[str, "ConditionCoverage"]] = None,
        partial_tagged_rows: Optional[List["EventRow"]] = None,
        partial_raw_rows: Optional[List[Dict[str, Any]]] = None,
    ):
        super().__init__(f"{code}: {detail}" if detail else code)
        self.code = code
        self.detail = detail
        self.partial_coverage = partial_coverage or {}
        self.partial_tagged_rows = partial_tagged_rows or []
        self.partial_raw_rows = partial_raw_rows or []


def canonical_int(value: Any) -> int:
    if value is None:
        raise DataExportPrecisionLoss("canonical_int received None")
    if isinstance(value, bool):
        raise DataExportPrecisionLoss(f"bool is not a token/amount: {value!r}")
    if isinstance(value, float):
        raise DataExportPrecisionLoss(f"float token/amount not string-safe: {value!r}")
    s = str(value).strip()
    if s == "":
        raise DataExportPrecisionLoss("canonical_int received empty string")
    if _SCI_RE.search(s):
        raise DataExportPrecisionLoss(f"scientific notation (precision lost): {s!r}")
    if "." in s:
        head, _, tail = s.partition(".")
        if tail.strip("0") != "" or not _INT_RE.match(head or "0"):
            raise DataExportPrecisionLoss(f"non-integer / float-mangled value: {s!r}")
        s = head if head != "" else "0"
    if not _INT_RE.match(s):
        raise DataExportPrecisionLoss(f"non-integer value: {s!r}")
    return int(s)


def parse_ts_utc(value: Any) -> float:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    s = str(value).strip()
    if re.match(r"^[0-9]+(\.[0-9]+)?$", s):
        return float(s)
    s2 = s.replace(" UTC", "").replace("Z", "").strip()
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(s2, fmt).replace(tzinfo=timezone.utc).timestamp()
        except ValueError:
            continue
    raise ValueError(f"unparseable timestamp: {value!r}")


# ---------------------------------------------------------------------------
# Manifest loading (pure logic - manifest itself was already validated by the
# builder; this module re-checks only what it needs to enforce caps/filters)
# ---------------------------------------------------------------------------
@dataclass
class ManifestEntry:
    condition_id: str
    side_0_token_id: str
    side_1_token_id: str
    window_start_utc: str
    window_end_utc: str
    per_condition_row_cap: int
    global_row_cap: int
    source_table_version: str = ""


def load_manifest(manifest_doc: Dict[str, Any]) -> Dict[str, ManifestEntry]:
    out: Dict[str, ManifestEntry] = {}
    for rec in manifest_doc.get("conditions", []):
        out[rec["condition_id"]] = ManifestEntry(
            condition_id=rec["condition_id"],
            side_0_token_id=rec["side_0_token_id"],
            side_1_token_id=rec["side_1_token_id"],
            window_start_utc=rec["window_start_utc"],
            window_end_utc=rec["window_end_utc"],
            per_condition_row_cap=int(rec["per_condition_row_cap"]),
            global_row_cap=int(rec["global_row_cap"]),
            source_table_version=rec.get("source_table_version", ""),
        )
    return out


# ---------------------------------------------------------------------------
# Event row validation + side tagging
# ---------------------------------------------------------------------------
@dataclass
class EventRow:
    condition_id: str
    tx_hash: str
    block_time: float
    maker_asset_id: str
    taker_asset_id: str
    maker_amount_filled: int
    taker_amount_filled: int
    source_provenance: str
    ordering_key: Optional[str] = None
    matched_side: str = "UNRESOLVED"  # side_0 | side_1 | BOTH | UNRESOLVED


def validate_and_tag_row(raw: Dict[str, Any], manifest: ManifestEntry) -> EventRow:
    missing = [f for f in REQUIRED_EVENT_FIELDS if raw.get(f) in (None, "")]
    if missing:
        raise CanaryHalt(C1_SOURCE_SCHEMA_UNVERIFIED, f"missing fields {missing} in row {raw}")

    try:
        maker_asset = str(raw["makerAssetId"]).strip()
        taker_asset = str(raw["takerAssetId"]).strip()
        maker_amt = canonical_int(raw["makerAmountFilled"])
        taker_amt = canonical_int(raw["takerAmountFilled"])
        canonical_int(maker_asset)
        canonical_int(taker_asset)
    except DataExportPrecisionLoss as exc:
        raise CanaryHalt(C1_SOURCE_SCHEMA_UNVERIFIED, str(exc)) from exc

    bt = parse_ts_utc(raw["block_time"])

    is_side0 = maker_asset == manifest.side_0_token_id or taker_asset == manifest.side_0_token_id
    is_side1 = maker_asset == manifest.side_1_token_id or taker_asset == manifest.side_1_token_id
    if is_side0 and is_side1:
        matched = "BOTH"
    elif is_side0:
        matched = "side_0"
    elif is_side1:
        matched = "side_1"
    else:
        matched = "UNRESOLVED"

    return EventRow(
        condition_id=raw["condition_id"],
        tx_hash=str(raw["tx_hash"]).strip(),
        block_time=bt,
        maker_asset_id=maker_asset,
        taker_asset_id=taker_asset,
        maker_amount_filled=maker_amt,
        taker_amount_filled=taker_amt,
        source_provenance=str(raw["source_provenance"]),
        ordering_key=raw.get("ordering_key"),
        matched_side=matched,
    )


# ---------------------------------------------------------------------------
# Core reconciliation
# ---------------------------------------------------------------------------
@dataclass
class ConditionCoverage:
    condition_id: str
    dune_rows_in_window: int = 0
    dune_tx_hashes: Set[str] = field(default_factory=set)
    local_tx_hashes: Set[str] = field(default_factory=set)
    unresolved_side_rows: int = 0

    @property
    def dune_only_tx_hashes(self) -> Set[str]:
        return self.dune_tx_hashes - self.local_tx_hashes

    @property
    def local_only_tx_hashes(self) -> Set[str]:
        return self.local_tx_hashes - self.dune_tx_hashes

    @property
    def overlap_tx_hashes(self) -> Set[str]:
        return self.dune_tx_hashes & self.local_tx_hashes


def run_canary(
    manifest: Dict[str, ManifestEntry],
    event_rows_raw: Sequence[Dict[str, Any]],
    local_tx_hashes_by_condition: Dict[str, Set[str]],
    require_ordering_key: bool = False,
) -> Tuple[Dict[str, ConditionCoverage], List[EventRow]]:
    """Pure-logic reconciliation core. Raises CanaryHalt with a typed code on
    any hard stop; caller is responsible for persisting whatever partial
    coverage dict exists before propagating the halt (persist-before-halt).

    An empty `event_rows_raw` is itself a distinct halt (`C1_SOURCE_EMPTY`),
    checked before anything else - it must never fall through to a clean/clear
    result. Zero rows is not evidence of anything and must be reported as such,
    not silently treated as a vacuously successful pass."""
    if not event_rows_raw:
        raise CanaryHalt(C1_SOURCE_EMPTY, "Dune CSV export contained zero event rows")

    coverage: Dict[str, ConditionCoverage] = {
        cid: ConditionCoverage(condition_id=cid, local_tx_hashes=set(local_tx_hashes_by_condition.get(cid, set())))
        for cid in manifest
    }
    tagged_rows: List[EventRow] = []
    raw_rows_seen: List[Dict[str, Any]] = []
    global_count = 0
    global_cap = min((m.global_row_cap for m in manifest.values()), default=0)

    try:
        for raw in event_rows_raw:
            raw_rows_seen.append(raw)
            cid = raw.get("condition_id")
            if cid not in manifest:
                # Out-of-manifest condition in the CSV is itself a bounding
                # failure - the query returned something outside the fixed
                # scope requested.
                raise CanaryHalt(C1_INDEXER_SHAPED, f"row for unrequested condition_id {cid!r}")
            m = manifest[cid]

            row = validate_and_tag_row(raw, m)

            if not (parse_ts_utc(m.window_start_utc) <= row.block_time <= parse_ts_utc(m.window_end_utc)):
                raise CanaryHalt(
                    C1_INDEXER_SHAPED,
                    f"row block_time {row.block_time} outside fixed window for {cid!r}",
                )
            if require_ordering_key and row.ordering_key in (None, ""):
                raise CanaryHalt(C1_ORDERING_KEY_MISSING, f"no ordering key for {cid!r} row {row.tx_hash}")

            cov = coverage[cid]
            cov.dune_rows_in_window += 1
            cov.dune_tx_hashes.add(row.tx_hash)
            if row.matched_side == "UNRESOLVED":
                cov.unresolved_side_rows += 1
            tagged_rows.append(row)
            global_count += 1

            if cov.dune_rows_in_window > m.per_condition_row_cap:
                raise CanaryHalt(
                    C1_ROW_EXPLOSION,
                    f"{cid!r} exceeded per_condition_row_cap {m.per_condition_row_cap}",
                )
            if global_count > global_cap:
                raise CanaryHalt(C1_ROW_EXPLOSION, f"global row count exceeded cap {global_cap}")

        # Local-reproduction check: if every condition's Dune tx_hash set is a
        # subset of (or equal to) its local tx_hash set - i.e. Dune surfaced
        # nothing local didn't already have, for every condition - the pilot
        # failed to test missing coverage in practice. event_rows_raw is
        # guaranteed non-empty here (the C1_SOURCE_EMPTY check above already
        # handled that).
        any_new_found = any(cov.dune_only_tx_hashes for cov in coverage.values())
        if not any_new_found:
            raise CanaryHalt(
                C1_LOCAL_TX_HASH_REPRODUCTION_ONLY,
                "no condition's Dune sample surfaced a tx_hash absent from local trades",
            )
    except CanaryHalt as halt:
        # Persist-before-halt: attach whatever was accumulated so far so the
        # caller can still write row-level artifacts on a hard stop, not only
        # on a clean run.
        halt.partial_coverage = coverage
        halt.partial_tagged_rows = tagged_rows
        halt.partial_raw_rows = raw_rows_seen
        raise

    return coverage, tagged_rows


# ---------------------------------------------------------------------------
# Output writers (persist-before-halt)
# ---------------------------------------------------------------------------
def write_coverage_outputs(
    out_dir: str,
    coverage: Dict[str, ConditionCoverage],
    outcome: str,
    detail: str = "",
) -> None:
    os.makedirs(out_dir, exist_ok=True)
    result = {
        "phase": PHASE,
        "authorized_scope": AUTHORIZED_SCOPE,
        "outcome": outcome,
        "detail": detail,
        "by_condition": {
            cid: {
                "dune_rows_in_window": cov.dune_rows_in_window,
                "dune_only_tx_hash_count": len(cov.dune_only_tx_hashes),
                "local_only_tx_hash_count": len(cov.local_only_tx_hashes),
                "overlap_tx_hash_count": len(cov.overlap_tx_hashes),
                "unresolved_side_rows": cov.unresolved_side_rows,
            }
            for cid, cov in coverage.items()
        },
    }
    with open(os.path.join(out_dir, "c1a_canary_result.json"), "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2)

    with open(os.path.join(out_dir, "c1a_canary_by_condition.csv"), "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(
            [
                "condition_id",
                "dune_rows_in_window",
                "dune_only_tx_hash_count",
                "local_only_tx_hash_count",
                "overlap_tx_hash_count",
                "unresolved_side_rows",
            ]
        )
        for cid, cov in coverage.items():
            w.writerow(
                [
                    cid,
                    cov.dune_rows_in_window,
                    len(cov.dune_only_tx_hashes),
                    len(cov.local_only_tx_hashes),
                    len(cov.overlap_tx_hashes),
                    cov.unresolved_side_rows,
                ]
            )

    with open(os.path.join(out_dir, "c1a_canary_result.md"), "w", encoding="utf-8") as fh:
        fh.write(f"# C1A canary result\n\n**Outcome:** `{outcome}`\n\n")
        if detail:
            fh.write(f"{detail}\n\n")
        fh.write(
            "This is a coverage diagnostic only. It is not a price-source "
            "viability verdict and does not compute or persist any price.\n"
        )


ROW_LEVEL_FIELDS = (
    "condition_id",
    "tx_hash",
    "block_time",
    "source_provenance",
    "makerAssetId",
    "takerAssetId",
    "makerAmountFilled",
    "takerAmountFilled",
    "ordering_key",
    "matched_side",
    "tx_hash_relation",
)


def write_row_level_artifacts(
    out_dir: str,
    raw_rows: Sequence[Dict[str, Any]],
    tagged_rows: Sequence[EventRow],
    coverage: Dict[str, ConditionCoverage],
) -> None:
    """Persist row-level evidence, bounded to the C1A canary only (patch
    requirement 4). Two artifacts:

    - `option_c_c1a_raw_rows_sample.csv` - the raw Dune CSV rows as ingested,
      unmodified, for audit (bounded by the same hard caps as the run itself,
      so "sample" here means "the whole bounded set," not a sub-sample).
    - `option_c_c1a_tagged_rows.csv` - one row per validated/tagged event row,
      with `matched_side` and `tx_hash_relation` (DUNE_ONLY / OVERLAP), PLUS a
      synthetic row per LOCAL_ONLY tx_hash (present locally, never returned by
      Dune) with only condition_id/tx_hash/tx_hash_relation populated - the
      event fields for a LOCAL_ONLY row are unknown by construction, since
      Dune never returned that row.

    Called even on a halt (whatever raw_rows/tagged_rows exist at halt time),
    consistent with persist-before-halt discipline.
    """
    os.makedirs(out_dir, exist_ok=True)

    with open(
        os.path.join(out_dir, "option_c_c1a_raw_rows_sample.csv"), "w", newline="", encoding="utf-8"
    ) as fh:
        fieldnames = list(REQUIRED_EVENT_FIELDS) + ["ordering_key"]
        w = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        for raw in raw_rows:
            w.writerow({k: raw.get(k, "") for k in fieldnames})

    with open(
        os.path.join(out_dir, "option_c_c1a_tagged_rows.csv"), "w", newline="", encoding="utf-8"
    ) as fh:
        w = csv.DictWriter(fh, fieldnames=list(ROW_LEVEL_FIELDS))
        w.writeheader()
        for row in tagged_rows:
            cov = coverage.get(row.condition_id)
            if cov is not None and row.tx_hash in cov.local_tx_hashes:
                relation = REL_OVERLAP
            else:
                relation = REL_DUNE_ONLY
            w.writerow(
                {
                    "condition_id": row.condition_id,
                    "tx_hash": row.tx_hash,
                    "block_time": row.block_time,
                    "source_provenance": row.source_provenance,
                    "makerAssetId": row.maker_asset_id,
                    "takerAssetId": row.taker_asset_id,
                    "makerAmountFilled": row.maker_amount_filled,
                    "takerAmountFilled": row.taker_amount_filled,
                    "ordering_key": row.ordering_key or "",
                    "matched_side": row.matched_side,
                    "tx_hash_relation": relation,
                }
            )
        # LOCAL_ONLY: present locally, never returned by Dune at all. Event
        # fields are unknown (Dune never gave us that row); only identity and
        # relation are recorded.
        for cid, cov in coverage.items():
            for tx in sorted(cov.local_only_tx_hashes):
                w.writerow(
                    {
                        "condition_id": cid,
                        "tx_hash": tx,
                        "block_time": "",
                        "source_provenance": "",
                        "makerAssetId": "",
                        "takerAssetId": "",
                        "makerAmountFilled": "",
                        "takerAmountFilled": "",
                        "ordering_key": "",
                        "matched_side": "N/A",
                        "tx_hash_relation": REL_LOCAL_ONLY,
                    }
                )


# ---------------------------------------------------------------------------
# Lazy real-data loader for the local-reproduction comparison (Claude does not
# execute this path)
# ---------------------------------------------------------------------------
class LocalTxHashLoader:
    def __init__(self, root: str):
        self.root = root

    def load(
        self, manifest: Dict[str, ManifestEntry]
    ) -> Dict[str, Set[str]]:
        from pm_research.data.store import Store  # lazy

        wanted = set(manifest.keys())
        df = Store(self.root).load_trades()
        df = df[df["condition_id"].isin(wanted)]
        out: Dict[str, Set[str]] = defaultdict(set)
        for cid, grp in df.groupby("condition_id"):
            cid = str(cid)
            m = manifest.get(cid)
            if m is None:
                continue
            ws, we = parse_ts_utc(m.window_start_utc), parse_ts_utc(m.window_end_utc)
            for tx, ts in zip(grp["tx_hash"].astype(str), grp["traded_at"]):
                try:
                    t = parse_ts_utc(ts)
                except ValueError:
                    continue
                if ws <= t <= we:
                    out[cid].add(tx)
        return dict(out)


# ---------------------------------------------------------------------------
# CLI (real run is a user-run task; Claude does not invoke this)
# ---------------------------------------------------------------------------
def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Reconcile a Dune OrderFilled CSV export against the fixed C1A "
        "selector manifest and local trades. No network call. Real execution is "
        "a user-run task; the CSV must already have been fetched manually."
    )
    p.add_argument("--root", default=r"C:\b1\data", help="Local data store root (trades).")
    p.add_argument(
        "--manifest",
        required=True,
        help="Path to c1a_selector_manifest.json (output of price_source_option_c_c1a_manifest.py).",
    )
    p.add_argument(
        "--dune-csv",
        required=True,
        help="Path to the Dune CSV export fetched manually per DUNE_DATA_NOTES section 7.",
    )
    p.add_argument("--require-ordering-key", action="store_true", default=False)
    p.add_argument(
        "--out-dir",
        default=os.path.join("artifacts", "named_binary_probe", "price_source_option_c_c1a"),
    )
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)

    with open(args.manifest, "r", encoding="utf-8") as fh:
        manifest_doc = json.load(fh)
    manifest = load_manifest(manifest_doc)

    with open(args.dune_csv, "r", newline="", encoding="utf-8") as fh:
        event_rows_raw = list(csv.DictReader(fh))

    local_loader = LocalTxHashLoader(args.root)
    local_tx_hashes = local_loader.load(manifest)

    try:
        coverage, tagged_rows = run_canary(
            manifest, event_rows_raw, local_tx_hashes, require_ordering_key=args.require_ordering_key
        )
    except CanaryHalt as halt:
        # Persist-before-halt: write whatever partial coverage/row-level
        # evidence had accumulated before the halt (attached to the exception
        # by run_canary itself), not an empty result.
        write_coverage_outputs(args.out_dir, halt.partial_coverage, halt.code, str(halt))
        write_row_level_artifacts(args.out_dir, halt.partial_raw_rows, halt.partial_tagged_rows, halt.partial_coverage)
        print(f"C1A canary HALTED: {halt.code} - {halt}")
        return 1

    # A non-halt run is reported as EXECUTED_NEEDS_REVIEW, never DESIGN_CLEAR.
    # This module never self-certifies design-clear status - that label is
    # applied by the Orchestrator only after reviewing these artifacts by hand.
    write_coverage_outputs(args.out_dir, coverage, C1_CANARY_EXECUTED_NEEDS_REVIEW)
    write_row_level_artifacts(args.out_dir, event_rows_raw, tagged_rows, coverage)
    print(f"C1A canary: {C1_CANARY_EXECUTED_NEEDS_REVIEW} -> {args.out_dir} (Orchestrator review required)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
